### ISSUE TITLE
Update for compatibility with Remixv3 / RR7 - Remix auth v4.0.0

### ISSUE THREAD

**Issue by 4FunAndProfit** [manaty226/remix-auth-openid#2]
Hello!!

Thanks a lot for this great project ! 

Will you add compatibility with RR7 and new remix auth ? 

See:
- https://github.com/sergiodxa/remix-auth/releases/tag/v4.0.0 
- https://reactrouter.com/upgrading/remix 

Thanks again ! :) 

Have a nice day

**Comment by manaty226** [comment]
Thanks for this issue.

I intend to upgrade this library for Remix v3 and React Router v7.
Thus, I will check the documents later and then I'll try to migrate this library.

**Comment by manaty226** [comment]
@4FunAndProfit 
This library is finally upgraded to Remix Auth v4!
Your issue encourage me to upgrade this repo, thanks.
I close this issue.

README.md and [starter example](https://github.com/manaty226/remix-auth-openid-example/tree/main) are now prepared for upgraded version.
